# Generated by Django 5.2.5 on 2025-08-08 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_system_user',
            new_name='is_staff',
        ),
    ]
